Fix error in PanelCorner._findLeftmostButton.
has_style_class_name can be null for some children:

    JS ERROR: Exception in callback for signal: updated: TypeError: children[index].has_style_class_name is not a function
    _findLeftmostButton@resource:///org/gnome/shell/ui/panel.js:546:15
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    _findLeftmostButton@resource:///org/gnome/shell/ui/panel.js:548:20
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    _findLeftmostButton@resource:///org/gnome/shell/ui/panel.js:548:20
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    _findLeftmostButton@resource:///org/gnome/shell/ui/panel.js:548:20
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    _findLeftmostButton@resource:///org/gnome/shell/ui/panel.js:548:20
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    _findLeftmostButton@resource:///org/gnome/shell/ui/panel.js:548:20
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    setStyleParent@resource:///org/gnome/shell/ui/panel.js:567:22
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    _updatePanel@resource:///org/gnome/shell/ui/panel.js:1076:13
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    _emit@resource:///org/gnome/gjs/modules/signals.js:128:27
    _sync@resource:///org/gnome/shell/ui/sessionMode.js:206:9
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    pushMode@resource:///org/gnome/shell/ui/sessionMode.js:168:9
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    activate@resource:///org/gnome/shell/ui/screenShield.js:1279:17
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    lock@resource:///org/gnome/shell/ui/screenShield.js:1328:9
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    _prepareForSleep@resource:///org/gnome/shell/ui/screenShield.js:731:17
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    _emit@resource:///org/gnome/gjs/modules/signals.js:128:27
    _prepareForSleep@resource:///org/gnome/shell/misc/loginManager.js:180:9
    wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
    _emit@resource:///org/gnome/gjs/modules/signals.js:128:27

Skip them when this happens.