meson: Bump gjs required version to 1.57.4
gnome-shell uses `gjs_profiler_set_fd()` which appeared in gjs-1.57.4
but meson checked for gjs-1.57.3, so the build fails with:

```
../../../../src/gnome/gnome-shell/src/main.c: In function
‘shell_profiler_init’:
../../../../src/gnome/gnome-shell/src/main.c:236:11:
warning: implicit declaration of function ‘gjs_profiler_set_fd’; did
you mean ‘gjs_profiler_stop’? [-Wimplicit-function-declaration]
  236 |           gjs_profiler_set_fd (profiler, fd);
      |           ^~~~~~~~~~~~~~~~~~~
      |           gjs_profiler_stop
../../../../src/gnome/gnome-shell/src/main.c:236:11: warning: nested
extern declaration of ‘gjs_profiler_set_fd’ [-Wnested-externs]
```

Bump gjs required version to 1.57.4 to avoid the issue.

Closes: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1412