calendar-server: Fix build failure with libical 4
Fix the following build error with libical 4 due to function signature changes and renames:

    error: passing argument 4 of 'get_time_from_property' from incompatible pointer type [-Wincompatible-pointer-types]
    note: expected 'ICalTime * (*)(ICalProperty *)' but argument is of type 'ICalTime * (*)(const ICalProperty *)'

and

    error: implicit declaration of function ‘i_cal_duration_as_int’; did you mean ‘i_cal_duration_is_neg’? [-Wimplicit-function-declaration]

Link: https://github.com/libical/libical/blob/4.0/docs/MigrationGuide_to_4.md
Part-of: <https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/4215>
(cherry picked from commit b34766f3992c7616b7816a47249fb463c053e5fa)